EnglynionBedd/Controllers/EnglynController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EnglynionBedd.Endidau;
using EnglynionBedd.Gwasanaethau;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EnglynionBedd.Controllers
{
    [Authorize]
    public class EnglynController : Controller
    {
        private readonly ICronfaEnglynion _cronfaEnglynion;

        public EnglynController(ICronfaEnglynion cronfaEnglynion)
        {
            _cronfaEnglynion = cronfaEnglynion;
        }

        [HttpGet]
        public async Task<IActionResult> RhestruEnglynion()
        {
            var rhestrEnglynion = await _cronfaEnglynion.AdalwEnglynion();
            return View(rhestrEnglynion);
        }

        // GET: Englyn/Manylion/5
        public async Task<IActionResult> Manylion(string id)
        {
            var englyn = await _cronfaEnglynion.AdalwEnglyn(id);
            return View(englyn);
        }

        // GET: Englyn/Golygu/5
        public async Task<IActionResult> Golygu(string id)
        {
            var englyn = await _cronfaEnglynion.AdalwEnglyn(id);
            return View(englyn);
        }

        // POST: Englyn/Golygu/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Golygu(Englyn englyn)
        {
            await _cronfaEnglynion.GolyguEnglyn(englyn);
            return RedirectToAction(nameof(RhestruEnglynion));
        }

        // GET: Englyn/Diddymu/5
        public ActionResult Diddymu(int id)
        {
            return View();
        }

        // POST: Englyn/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Diddymu(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(RhestruEnglynion));
            }
            catch
            {
                return View();
            }
        }
    }
}

EnglynionBedd/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnglynionBedd</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />"
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Englynion Bedd</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="LlwythoDelwedd">Llwytho Delwedd Newydd</a></li>
                    <li><a asp-controller="Englyn" asp-action="RhestruEnglynion">Rhestr Englynion</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EnglynionBedd</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/bootstrap-filestyle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/bootstrap-filestyle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>